### ISSUE TITLE
How to add an account to the DB

### ISSUE THREAD

**Issue by vzrd23** [adann0/jiva#2]
Hello Adann0,

Thanks for your work.

Can you please let me know how to add an account to the DB? Tried many ways, reloading vagrant, rebuilding, etc with no success.

Thank you again.

**Comment by adann0** [comment]
Hi vzrd23,

This feature is sadly not provided (by something friendly like a command line interface, you can hack arround to make it happen ofc - The account table is stored into the login database).

Accounts are provided in docs/accounts.txt, and the server should only run in local, so it should not be a security issue to use these public accounts to test the server.

**Comment by adann0** [comment]
Hi vzrd23,

This feature is sadly not provided (by something friendly like a command line interface, you can hack arround to make it happen ofc - The account table is stored into the login database, and you can easilly find into the code the lines that show the encryptions and verifications methods for the passwords).

Otherwise, accounts are provided in docs/accounts.txt, and as the server should only run in local, it should not be a security issue to use these public accounts to test the server.

**Comment by vzrd23** [comment]
Hey Adann0,

Yeah I supposed that but when I change the db accounts and run vagrant they
just dont access.

Only access with accounts like cra, iop,etc

I ve also tried to modify at first the files before deploying but Vagrant
still takes your accounts that I also deleted and they are still accesible
lol

If you can light the path hahahha that would be great

Another thing. As we use remastered client version. Do the animations are
40 fps like official? Because my VM seems a little bit laggy although it
has 6 core 12 ram.

I know that we should not virtualize it but it worked for me lol

Thanks again

**Comment by adann0** [comment]
I could make a Python script, in the next weeks, to create new accounts.

The animations files come directly with the Client, downloaded from the official sources. So if the Client is laggy, I guess that it's because of the Virtual Machine (Video Memory, 3D Acceleration, and that kind of stuff).

**Comment by vzrd23** [comment]
That would be great for the other people, I just need like 2 custom
accounts or 3:

* admin
* player1
* player2

I'm actually trying to deploy again and change login.sql details before
anything

Anyway I'll be travelling in 2 days so I won't be able to play much.

Looking for any update.

Good work and you can close the "Issue"

Thanks again

**Comment by adann0** [comment]
Feature added.
